import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'iPhone 15 Pro (128GB, Natural Titanium)',
    brand: 'Apple',
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1696446701796-da61225697cc?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'The iPhone 15 Pro is the first iPhone to feature an aerospace-grade titanium design, using the same alloy that spacecraft use for missions to Mars.',
    rating: 4.8,
    reviewCount: 12450,
    stockStatus: 'IN_STOCK',
    specifications: {
      'Display': '6.1-inch Super Retina XDR',
      'Chip': 'A17 Pro chip',
      'Camera': '48MP Main | Ultra Wide | Telephoto',
      'Battery': 'Up to 23 hours video playback'
    },
    platforms: [
      {
        name: 'Amazon',
        price: 124900,
        originalPrice: 134900,
        url: 'https://www.amazon.in/s?k=iphone+15+pro',
        seller: 'Appario Retail',
        sellerRating: 4.5,
        ethicsScore: 8,
        sustainabilityRating: 7,
        deliveryDays: 1,
        isPrime: true,
      },
      {
        name: 'Flipkart',
        price: 122999,
        originalPrice: 134900,
        url: 'https://www.flipkart.com/search?q=iphone+15+pro',
        seller: 'SuperComNet',
        sellerRating: 4.2,
        ethicsScore: 6,
        sustainabilityRating: 5,
        deliveryDays: 3,
        isPrime: false,
      },
      {
        name: 'Blinkit',
        price: 126900,
        originalPrice: 134900,
        url: 'https://blinkit.com/s/?q=iphone+15+pro',
        seller: 'QuickStore',
        sellerRating: 4.8,
        ethicsScore: 7,
        sustainabilityRating: 4,
        deliveryDays: 0,
        isPrime: false,
      }
    ],
    historicalData: [
      { date: '2024-01-01', price: 134900 },
      { date: '2024-01-15', price: 132000 },
      { date: '2024-02-01', price: 129900 },
      { date: '2024-02-15', price: 128000 },
      { date: '2024-03-01', price: 124900 },
      { date: '2024-03-08', price: 122999 },
    ]
  },
  {
    id: '2',
    name: 'Sony WH-1000XM5 Wireless Headphones',
    brand: 'Sony',
    category: 'Audio',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Industry-leading noise cancellation with two processors controlling eight microphones, and exceptional call quality.',
    rating: 4.7,
    reviewCount: 8900,
    stockStatus: 'LOW_STOCK',
    specifications: {
      'Battery Life': 'Up to 30 hours',
      'Noise Cancelling': 'Yes (Active)',
      'Connectivity': 'Bluetooth 5.2',
      'Weight': '250g'
    },
    platforms: [
      {
        name: 'Amazon',
        price: 29990,
        originalPrice: 34990,
        url: 'https://www.amazon.in/s?k=sony+wh-1000xm5',
        seller: 'Cloudtail',
        sellerRating: 4.6,
        ethicsScore: 7,
        sustainabilityRating: 8,
        deliveryDays: 2,
        isPrime: true,
      },
      {
        name: 'Tata CLiQ',
        price: 28500,
        originalPrice: 34990,
        url: 'https://www.tatacliq.com/search/?searchCategory=all&text=sony+wh-1000xm5',
        seller: 'Tata Retail',
        sellerRating: 4.7,
        ethicsScore: 9,
        sustainabilityRating: 8,
        deliveryDays: 4,
        isPrime: false,
      },
      {
        name: 'Zepto',
        price: 31000,
        originalPrice: 34990,
        url: 'https://zeptonow.com/s/?q=sony+wh-1000xm5',
        seller: 'FastGadgets',
        sellerRating: 4.5,
        ethicsScore: 6,
        sustainabilityRating: 5,
        deliveryDays: 0,
        isPrime: false,
      }
    ],
    historicalData: [
      { date: '2024-01-01', price: 34990 },
      { date: '2024-01-15', price: 32000 },
      { date: '2024-02-01', price: 31000 },
      { date: '2024-02-15', price: 29990 },
      { date: '2024-03-01', price: 28500 },
    ]
  },
  {
    id: '3',
    name: 'MacBook Air M3 (13-inch, 8GB RAM, 256GB SSD)',
    brand: 'Apple',
    category: 'Computers',
    image: 'https://images.unsplash.com/photo-1517336712461-481a2f83276a?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1611186871348-b1ec696e5237?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'The M3 chip brings even greater capabilities to the superportable 13-inch MacBook Air. With up to 18 hours of battery life.',
    rating: 4.9,
    reviewCount: 3200,
    stockStatus: 'IN_STOCK',
    specifications: {
      'Display': '13.6-inch Liquid Retina',
      'Chip': 'Apple M3 chip',
      'Memory': '8GB Unified Memory',
      'Storage': '256GB SSD'
    },
    platforms: [
      {
        name: 'Amazon',
        price: 114900,
        originalPrice: 114900,
        url: 'https://www.amazon.in/s?k=macbook+air+m3',
        seller: 'Appario Retail',
        sellerRating: 4.5,
        ethicsScore: 8,
        sustainabilityRating: 7,
        deliveryDays: 1,
        isPrime: true,
      },
      {
        name: 'Croma',
        price: 112900,
        originalPrice: 114900,
        url: 'https://www.croma.com/search/?text=macbook+air+m3',
        seller: 'Croma Retail',
        sellerRating: 4.6,
        ethicsScore: 7,
        sustainabilityRating: 6,
        deliveryDays: 2,
        isPrime: false,
      },
      {
        name: 'Flipkart',
        price: 113500,
        originalPrice: 114900,
        url: 'https://www.flipkart.com/search?q=macbook+air+m3',
        seller: 'SuperComNet',
        sellerRating: 4.3,
        ethicsScore: 6,
        sustainabilityRating: 5,
        deliveryDays: 3,
        isPrime: false,
      }
    ],
    historicalData: [
      { date: '2024-01-01', price: 114900 },
      { date: '2024-02-01', price: 114900 },
      { date: '2024-03-01', price: 114900 },
    ]
  },
  {
    id: '4',
    name: 'Samsung Galaxy S24 Ultra (256GB, Titanium Gray)',
    brand: 'Samsung',
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1583573636246-18cb2246697f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1592890288564-76628a30a657?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Welcome to the era of mobile AI. With Galaxy S24 Ultra in your hands, you can unleash whole new levels of creativity, productivity and possibility.',
    rating: 4.8,
    reviewCount: 15600,
    stockStatus: 'IN_STOCK',
    specifications: {
      'Display': '6.8-inch Dynamic AMOLED 2X',
      'Processor': 'Snapdragon 8 Gen 3',
      'Camera': '200MP Main | 50MP Periscope',
      'Battery': '5000mAh'
    },
    platforms: [
      {
        name: 'Amazon',
        price: 129999,
        originalPrice: 139999,
        url: 'https://www.amazon.in/s?k=samsung+galaxy+s24+ultra',
        seller: 'STPL',
        sellerRating: 4.4,
        ethicsScore: 7,
        sustainabilityRating: 8,
        deliveryDays: 2,
        isPrime: true,
      },
      {
        name: 'Samsung Store',
        price: 129999,
        originalPrice: 139999,
        url: 'https://www.samsung.com/in/smartphones/galaxy-s24-ultra/buy/',
        seller: 'Samsung India',
        sellerRating: 4.9,
        ethicsScore: 8,
        sustainabilityRating: 9,
        deliveryDays: 3,
        isPrime: false,
      },
      {
        name: 'Flipkart',
        price: 128990,
        originalPrice: 139999,
        url: 'https://www.flipkart.com/search?q=samsung+galaxy+s24+ultra',
        seller: 'SuperComNet',
        sellerRating: 4.2,
        ethicsScore: 6,
        sustainabilityRating: 5,
        deliveryDays: 3,
        isPrime: false,
      }
    ],
    historicalData: [
      { date: '2024-01-01', price: 139999 },
      { date: '2024-01-15', price: 135000 },
      { date: '2024-02-01', price: 132000 },
      { date: '2024-02-15', price: 129999 },
      { date: '2024-03-01', price: 129999 },
    ]
  },
  {
    id: '5',
    name: 'Nike Air Jordan 1 Retro High OG',
    brand: 'Nike',
    category: 'Footwear',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'The Air Jordan 1 Retro High OG combines a classic design with premium materials for a timeless look that honors the original.',
    rating: 4.9,
    reviewCount: 25400,
    stockStatus: 'LOW_STOCK',
    specifications: {
      'Material': 'Leather Upper',
      'Cushioning': 'Air-Sole unit',
      'Outsole': 'Solid rubber',
      'Style': 'High-top'
    },
    platforms: [
      {
        name: 'Nike India',
        price: 16995,
        originalPrice: 16995,
        url: 'https://www.nike.com/in/w?q=air+jordan+1+retro+high+og',
        seller: 'Nike Official',
        sellerRating: 4.9,
        ethicsScore: 9,
        sustainabilityRating: 8,
        deliveryDays: 5,
        isPrime: false,
      },
      {
        name: 'Myntra',
        price: 15995,
        originalPrice: 16995,
        url: 'https://www.myntra.com/air-jordan-1-retro-high-og',
        seller: 'Nike Authorized',
        sellerRating: 4.7,
        ethicsScore: 8,
        sustainabilityRating: 7,
        deliveryDays: 3,
        isPrime: true,
      },
      {
        name: 'Ajio',
        price: 16495,
        originalPrice: 16995,
        url: 'https://www.ajio.com/search/?text=air+jordan+1+retro+high+og',
        seller: 'Reliance Retail',
        sellerRating: 4.6,
        ethicsScore: 7,
        sustainabilityRating: 6,
        deliveryDays: 2,
        isPrime: false,
      },
      {
        name: 'Meesho',
        price: 15499,
        originalPrice: 16995,
        url: 'https://www.meesho.com/search?q=air+jordan+1+retro+high+og',
        seller: 'FashionHub',
        sellerRating: 4.1,
        ethicsScore: 5,
        sustainabilityRating: 4,
        deliveryDays: 6,
        isPrime: false,
      }
    ],
    historicalData: [
      { date: '2024-01-01', price: 16995 },
      { date: '2024-02-01', price: 16995 },
      { date: '2024-03-01', price: 15499 },
    ]
  },
  {
    id: '6',
    name: 'Adidas Ultraboost Light Running Shoes',
    brand: 'Adidas',
    category: 'Footwear',
    image: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1595341888016-a392ef81b7de?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Experience epic energy with the new Ultraboost Light, our lightest Ultraboost ever.',
    rating: 4.7,
    reviewCount: 12300,
    stockStatus: 'IN_STOCK',
    specifications: {
      'Weight': '293g',
      'Midsole': 'Light BOOST',
      'Upper': 'PRIMEKNIT+',
      'Drop': '10mm'
    },
    platforms: [
      {
        name: 'Adidas Store',
        price: 18999,
        originalPrice: 18999,
        url: 'https://www.adidas.co.in/search?q=ultraboost+light',
        seller: 'Adidas India',
        sellerRating: 4.8,
        ethicsScore: 9,
        sustainabilityRating: 10,
        deliveryDays: 4,
        isPrime: false,
      },
      {
        name: 'Amazon',
        price: 17499,
        originalPrice: 18999,
        url: 'https://www.amazon.in/s?k=adidas+ultraboost+light',
        seller: 'Cloudtail',
        sellerRating: 4.6,
        ethicsScore: 7,
        sustainabilityRating: 8,
        deliveryDays: 2,
        isPrime: true,
      },
      {
        name: 'Flipkart',
        price: 17299,
        originalPrice: 18999,
        url: 'https://www.flipkart.com/search?q=adidas+ultraboost+light',
        seller: 'SuperComNet',
        sellerRating: 4.3,
        ethicsScore: 6,
        sustainabilityRating: 5,
        deliveryDays: 3,
        isPrime: false,
      },
      {
        name: 'Myntra',
        price: 17999,
        originalPrice: 18999,
        url: 'https://www.myntra.com/adidas-ultraboost-light',
        seller: 'Adidas Authorized',
        sellerRating: 4.7,
        ethicsScore: 8,
        sustainabilityRating: 7,
        deliveryDays: 2,
        isPrime: true,
      }
    ],
    historicalData: [
      { date: '2024-01-01', price: 18999 },
      { date: '2024-01-15', price: 18500 },
      { date: '2024-02-01', price: 17999 },
      { date: '2024-02-15', price: 17499 },
      { date: '2024-03-01', price: 17299 },
    ]
  },
  {
    id: '8',
    name: 'Men Cotton Slim Fit Casual Shirt',
    brand: 'Roadster',
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1589310243389-96a5483213a8?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'A versatile cotton slim fit shirt perfect for casual outings or office wear.',
    rating: 4.2,
    reviewCount: 4500,
    stockStatus: 'IN_STOCK',
    specifications: {
      'Material': '100% Cotton',
      'Fit': 'Slim Fit',
      'Sleeve': 'Long Sleeves',
      'Pattern': 'Solid'
    },
    platforms: [
      {
        name: 'Myntra',
        price: 899,
        originalPrice: 1499,
        url: 'https://www.myntra.com/shirts/roadster/roadster-men-blue-casual-shirt/1364628/buy',
        seller: 'TrueCom Retail',
        sellerRating: 4.5,
        ethicsScore: 7,
        sustainabilityRating: 6,
        deliveryDays: 3,
        isPrime: true,
      },
      {
        name: 'Flipkart',
        price: 799,
        originalPrice: 1499,
        url: 'https://www.flipkart.com/search?q=roadster+shirt',
        seller: 'RetailNet',
        sellerRating: 4.2,
        ethicsScore: 6,
        sustainabilityRating: 5,
        deliveryDays: 4,
        isPrime: false,
      },
      {
        name: 'Meesho',
        price: 450,
        originalPrice: 1499,
        url: 'https://www.meesho.com/search?q=cotton+shirt+men',
        seller: 'LocalWeaves',
        sellerRating: 3.8,
        ethicsScore: 4,
        sustainabilityRating: 3,
        deliveryDays: 7,
        isPrime: false,
      },
      {
        name: 'Amazon',
        price: 949,
        originalPrice: 1499,
        url: 'https://www.amazon.in/s?k=roadster+shirt',
        seller: 'Cloudtail',
        sellerRating: 4.6,
        ethicsScore: 7,
        sustainabilityRating: 8,
        deliveryDays: 2,
        isPrime: true,
      },
      {
        name: 'Ajio',
        price: 849,
        originalPrice: 1499,
        url: 'https://www.ajio.com/search/?text=roadster+shirt',
        seller: 'Reliance Retail',
        sellerRating: 4.4,
        ethicsScore: 7,
        sustainabilityRating: 6,
        deliveryDays: 3,
        isPrime: false,
      }
    ],
    historicalData: [
      { date: '2024-01-01', price: 1499 },
      { date: '2024-02-01', price: 999 },
      { date: '2024-03-01', price: 450 },
    ]
  },
  {
    id: '9',
    name: 'Noise ColorFit Pulse 3 Smartwatch',
    brand: 'Noise',
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1508685096489-7aac291ba597?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1508685096489-7aac291ba597?auto=format&fit=crop&w=800&q=80'
    ],
    description: '1.96" TFT Display, Single chip BT calling, 100+ sports modes, and up to 7-day battery life.',
    rating: 4.3,
    reviewCount: 32000,
    stockStatus: 'IN_STOCK',
    specifications: {
      'Display': '1.96 inch TFT',
      'Calling': 'BT Calling',
      'Battery': 'Up to 7 days',
      'Water Resistance': 'IP68'
    },
    platforms: [
      {
        name: 'Amazon',
        price: 1599,
        originalPrice: 4999,
        url: 'https://www.amazon.in/s?k=noise+colorfit+pulse+3',
        seller: 'Appario Retail',
        sellerRating: 4.5,
        ethicsScore: 8,
        sustainabilityRating: 7,
        deliveryDays: 1,
        isPrime: true,
      },
      {
        name: 'Flipkart',
        price: 1499,
        originalPrice: 4999,
        url: 'https://www.flipkart.com/search?q=noise+colorfit+pulse+3',
        seller: 'RetailNet',
        sellerRating: 4.3,
        ethicsScore: 6,
        sustainabilityRating: 5,
        deliveryDays: 2,
        isPrime: false,
      },
      {
        name: 'Meesho',
        price: 1299,
        originalPrice: 4999,
        url: 'https://www.meesho.com/search?q=noise+smartwatch',
        seller: 'GadgetZone',
        sellerRating: 3.9,
        ethicsScore: 5,
        sustainabilityRating: 4,
        deliveryDays: 5,
        isPrime: false,
      }
    ],
    historicalData: [
      { date: '2024-01-01', price: 4999 },
      { date: '2024-02-01', price: 1999 },
      { date: '2024-03-01', price: 1299 },
    ]
  },
  {
    id: '7',
    name: 'Anker 737 Power Bank (PowerCore 24K)',
    brand: 'Anker',
    category: 'Quick Commerce',
    image: 'https://images.unsplash.com/photo-1619134769032-e9d758323444?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1619134769032-e9d758323444?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Equipped with the latest Power Delivery 3.1 and bi-directional technology to quickly recharge the portable charger or get a 140W ultra-powerful charge.',
    rating: 4.8,
    reviewCount: 5400,
    stockStatus: 'IN_STOCK',
    specifications: {
      'Capacity': '24,000mAh',
      'Max Output': '140W',
      'Ports': '2x USB-C, 1x USB-A',
      'Display': 'Smart Digital Display'
    },
    platforms: [
      {
        name: 'Amazon',
        price: 13999,
        originalPrice: 15999,
        url: 'https://www.amazon.in/s?k=anker+737+power+bank',
        seller: 'Appario Retail',
        sellerRating: 4.5,
        ethicsScore: 8,
        sustainabilityRating: 7,
        deliveryDays: 1,
        isPrime: true,
      },
      {
        name: 'Blinkit',
        price: 14499,
        originalPrice: 15999,
        url: 'https://blinkit.com/s/?q=anker+737+power+bank',
        seller: 'QuickStore',
        sellerRating: 4.8,
        ethicsScore: 7,
        sustainabilityRating: 4,
        deliveryDays: 0,
        isPrime: false,
      },
      {
        name: 'Zepto',
        price: 14599,
        originalPrice: 15999,
        url: 'https://zeptonow.com/s/?q=anker+737+power+bank',
        seller: 'FastGadgets',
        sellerRating: 4.6,
        ethicsScore: 6,
        sustainabilityRating: 5,
        deliveryDays: 0,
        isPrime: false,
      }
    ],
    historicalData: [
      { date: '2024-01-01', price: 15999 },
      { date: '2024-02-01', price: 14999 },
      { date: '2024-03-01', price: 13999 },
    ]
  }
];
